require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RepostsController do

  # This should return the minimal set of attributes required to create a valid
  # Repost. As you add validations to Repost, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "post_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RepostsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all reposts as @reposts" do
      repost = Repost.create! valid_attributes
      get :index, {}, valid_session
      assigns(:reposts).should eq([repost])
    end
  end

  describe "GET show" do
    it "assigns the requested repost as @repost" do
      repost = Repost.create! valid_attributes
      get :show, {:id => repost.to_param}, valid_session
      assigns(:repost).should eq(repost)
    end
  end

  describe "GET new" do
    it "assigns a new repost as @repost" do
      get :new, {}, valid_session
      assigns(:repost).should be_a_new(Repost)
    end
  end

  describe "GET edit" do
    it "assigns the requested repost as @repost" do
      repost = Repost.create! valid_attributes
      get :edit, {:id => repost.to_param}, valid_session
      assigns(:repost).should eq(repost)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Repost" do
        expect {
          post :create, {:repost => valid_attributes}, valid_session
        }.to change(Repost, :count).by(1)
      end

      it "assigns a newly created repost as @repost" do
        post :create, {:repost => valid_attributes}, valid_session
        assigns(:repost).should be_a(Repost)
        assigns(:repost).should be_persisted
      end

      it "redirects to the created repost" do
        post :create, {:repost => valid_attributes}, valid_session
        response.should redirect_to(Repost.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved repost as @repost" do
        # Trigger the behavior that occurs when invalid params are submitted
        Repost.any_instance.stub(:save).and_return(false)
        post :create, {:repost => { "post_id" => "invalid value" }}, valid_session
        assigns(:repost).should be_a_new(Repost)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Repost.any_instance.stub(:save).and_return(false)
        post :create, {:repost => { "post_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested repost" do
        repost = Repost.create! valid_attributes
        # Assuming there are no other reposts in the database, this
        # specifies that the Repost created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Repost.any_instance.should_receive(:update).with({ "post_id" => "1" })
        put :update, {:id => repost.to_param, :repost => { "post_id" => "1" }}, valid_session
      end

      it "assigns the requested repost as @repost" do
        repost = Repost.create! valid_attributes
        put :update, {:id => repost.to_param, :repost => valid_attributes}, valid_session
        assigns(:repost).should eq(repost)
      end

      it "redirects to the repost" do
        repost = Repost.create! valid_attributes
        put :update, {:id => repost.to_param, :repost => valid_attributes}, valid_session
        response.should redirect_to(repost)
      end
    end

    describe "with invalid params" do
      it "assigns the repost as @repost" do
        repost = Repost.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Repost.any_instance.stub(:save).and_return(false)
        put :update, {:id => repost.to_param, :repost => { "post_id" => "invalid value" }}, valid_session
        assigns(:repost).should eq(repost)
      end

      it "re-renders the 'edit' template" do
        repost = Repost.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Repost.any_instance.stub(:save).and_return(false)
        put :update, {:id => repost.to_param, :repost => { "post_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested repost" do
      repost = Repost.create! valid_attributes
      expect {
        delete :destroy, {:id => repost.to_param}, valid_session
      }.to change(Repost, :count).by(-1)
    end

    it "redirects to the reposts list" do
      repost = Repost.create! valid_attributes
      delete :destroy, {:id => repost.to_param}, valid_session
      response.should redirect_to(reposts_url)
    end
  end

end
